import re
import struct
import sys
from binascii import crc32
from collections.abc import Mapping
from io import BytesIO, StringIO as unicodeIO
from typing import Any, TextIO

from .vdict import VDFDict as VDFDict

__version__ = ...
__author__ = ...
if sys.version_info[0] >= 3:
    string_type = str
    int_type = int
    BOMS = ...
    def strip_bom(line): ...

_unescape_char_map = ...
_escape_char_map = ...

def parse(
    fp: TextIO,
    mapper: type[dict[Any, Any]],
    merge_duplicate_keys: bool = True,
    escaped: bool = True,
) -> VDFDict: ...
def loads(s, **kwargs) -> dict[Any, Any]: ...
def load(fp, **kwargs) -> dict[Any, Any]: ...
def dumps(obj, pretty=..., escaped=...):  # -> str:
    ...
def dump(obj: dict[Any, Any], fp: TextIO, pretty: bool = False, escaped: bool = True) -> None: ...

class BASE_INT(int_type):
    def __repr__(self):  # -> str:
        ...

class UINT_64(BASE_INT): ...
class INT_64(BASE_INT): ...
class POINTER(BASE_INT): ...
class COLOR(BASE_INT): ...

BIN_NONE = ...
BIN_STRING = ...
BIN_INT32 = ...
BIN_FLOAT32 = ...
BIN_POINTER = ...
BIN_WIDESTRING = ...
BIN_COLOR = ...
BIN_UINT64 = ...
BIN_END = ...
BIN_INT64 = ...
BIN_END_ALT = ...

def binary_loads(b, mapper=..., merge_duplicate_keys=..., alt_format=..., raise_on_remaining=...) -> dict[Any, Any]: ...
def binary_load(fp, mapper=..., merge_duplicate_keys=..., alt_format=..., raise_on_remaining=...) -> dict[Any, Any]: ...
def binary_dumps(obj, alt_format=...) -> bytes: ...
def binary_dump(obj, fp, alt_format=...) -> None: ...
def vbkv_loads(s, mapper=..., merge_duplicate_keys=...) -> dict[Any, Any]: ...
def vbkv_dumps(obj) -> bytes: ...
