import collections.abc as _c
import sys
from collections.abc import Generator
from typing import Any

if sys.version_info[0] >= 3:
    _iter_values = ...
    _range = range
    _string_type = str
    class _kView(_c.KeysView):
        def __iter__(self): ...

    class _vView(_c.ValuesView):
        def __iter__(self): ...

    class _iView(_c.ItemsView):
        def __iter__(self): ...

class VDFDict(dict):
    def __init__(self, data=...) -> None: ...
    def __len__(self) -> int: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self) -> Generator[Any]: ...
    def __contains__(self, key):  # -> bool:
        ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def clear(self):  # -> None:
        ...
    def get(self, key, *args): ...
    def setdefault(self, key, default=...): ...
    def pop(self, key): ...
    def popitem(self):  # -> tuple[Any, Any]:
        ...
    def update(self, data=..., **kwargs):  # -> None:
        ...
    def iterkeys(self):  # -> Generator[Any, None, None]:
        ...
    def keys(self):  # -> _kView:
        ...
    def itervalues(self):  # -> Generator[Any, None, None]:
        ...
    def values(self):  # -> _vView:
        ...
    def iteritems(self):  # -> Generator[tuple[Any, Any], None, None]:
        ...
    def items(self):  # -> _iView:
        ...
    def get_all_for(self, key) -> list[Any]: ...
    def remove_all_for(self, key) -> None: ...
    def has_duplicates(self) -> bool: ...
