on:
  push:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BRANCH
        uses: actions/checkout@v3
      - name: FETCH MAIN 
        run: |
          git checkout gh-pages
          git pull

      - name: CREATE PULL REQUEST
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: gh-pages
      - name: ENABLE PR AUTOMERGE
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
